### ISSUE TITLE
Getting yellow warning: RNCNetInfo you're using the deprecated API

### ISSUE THREAD

**Issue by Nehal-29** [calvium/react-native-redux-connectivity#7]
Can you update your library to make it compatible with 0.60v. NetInfo Library methods and API calls has been changed
<img width="341" alt="Screenshot 2019-11-29 at 4 12 42 PM" src="https://user-images.githubusercontent.com/41570871/70209052-3362e680-1755-11ea-9df6-328ac246d679.png">
@richardbarrell-calvium

**Comment by Nehal-29** [comment]
@richardbarrell-calvium I've raised a PR for the same. Kindly have a look

**Comment by Nehal-29** [comment]
@benvium @richardhull @mattvot @pablocarrillo

**Comment by richardbarrell-calvium** [comment]
Hey, thank you for the PR. Apologies for the slow response, I've been on holiday. :)

I'm slightly surprised we're not also getting deprecation warnings for importing NetInfo from react-native instead of from the separate package at https://github.com/react-native-community/react-native-netinfo now.

**Comment by richardbarrell-calvium** [comment]
Update: we weren't getting the other deprecation warnings because that was fixed already too. Sweet.

Thank you!

**Comment by richardbarrell-calvium** [comment]
(This was fixed by PR #8)
